### ISSUE TITLE
Question about dev status

### ISSUE THREAD

**Issue by COLABORATI** [artemdemo/wordpress-restapi-angular2#1]
Hi, I just would like to know: is this a one-shot demo or do you plan to work on this on a longer time period? ARe you planning on adding features / supporting future wordpress versions /  developing on it?

Also: wouldn't it make sense to make this a wordpress theme and not put the whole wordpress code into repository?

**Comment by artemdemo** [comment]
No, I'm not planning to work on it.
Yeh, make repository with wordpress theme is better approach.
