### ISSUE TITLE
setup and compile suggestions

### ISSUE THREAD

**Issue by dolphinsd** [artemdemo/wordpress-restapi-angular2#2]
I know its work in progress. I tried to build, here are few issues:

1. Step 2 does not work on windows cli.
2. Step 4 - maybe better way to handle is to point to existing installation of wordpress
3. Step 6 - need to run npm install to get all dependencies.
4. Step 7 - theme is activated by build in step 6 puts files into wrong  directory. Also styles.css is not moved as well. 

Hope it helps.

**Comment by artemdemo** [comment]
Thanks, I'll look into it later.

**Comment by dolphinsd** [comment]
sounds good, try to run your previous version, it seems to be out of sync with reps. left you a note at contact us - u menya est interestni proekt, dai znat esli est vremay.

**Comment by dolphinsd** [comment]
Artem, try to reach out to you if you are interested or know someone, need
Angular/WP skills.

Thanks.
